### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'x' of null

### ISSUE THREAD

**Issue by zloysmiertniy** [msalsbery/OpenSeadragonImagingHelper#11] opened 2017-08-02 13:34 UTC
Hi, as soon as I try to create OSDimage helper it says

 Uncaught TypeError: Cannot read property 'x' of null (openseadragon-imaginghelper.min.js:5)
    at b.ImagingHelper.c (openseadragon-imaginghelper.min.js:5)
    at Object.handler (openseadragon.js:1243)
    at eventsource.js:162
    at a.Viewer.raiseEvent (eventsource.js:184)
    at j (viewer.js:581)
    at Object.b.success (viewer.js:633)
    at f (viewer.js:1460)
    at a.options (viewer.js:1472)
    at a.TileSource.success (viewer.js:2268)
    at Object.handler (tilesource.js:135)

**Comment by Ronalses** [comment] 2017-10-02 13:32
Hi!
Could you solve it?
I have the same problem.

**Comment by tdiprima** [comment] 2017-10-30 18:37
I think the problem is this:
If you're using OSD <= v2.1.0, there's an element in the "viewer" object called "contentSize", in which you get an x and a y.
That element is dropped in OSD v2.2.0.  Not sure if something else replaces it; I haven't gotten that far in researching this yet.  Tag &ndash; @iangilman.

**Comment by tdiprima** [comment] 2017-10-30 19:00
#### Update: 
Doesn't seem to make a difference if you initialize like:
`var imagingHelper = viewer.activateImagingHelper({viewer: viewer});`
or
`var imagingHelper = new OpenSeadragon.ImagingHelper({viewer: existingviewer});`

**Comment by iangilman** [comment] 2017-10-31 16:29
This issue is a result of https://github.com/msalsbery/OpenSeadragonImagingHelper/issues/9. Unfortunately, it doesn't look like @msalsbery has the bandwidth to fix it, but I think there are some ideas in that thread for how to do so.

**Comment by Ronalses** [comment] 2017-10-31 17:45
This worked for me.
`  function onOpen() {
        this._haveImage = true;
        this.imgWidth = this._viewer.source.dimensions.x;
        this.imgHeight = this._viewer.source.dimensions.y;
        this.imgAspectRatio = this.imgWidth / this.imgHeight;
        this._trackZoomPan();
    }`

**Comment by iangilman** [comment] 2017-11-01 16:50
@Ronalses Cool! Could you make a pull request with that?

**Comment by iangilman** [comment] 2017-11-01 16:53
Actually, looks like there's already a pull request for this: https://github.com/msalsbery/OpenSeadragonImagingHelper/pull/12

@birm @Ronalses Perhaps you can compare notes?

**Comment by iangilman** [comment] 2017-11-16 18:56
Fixed by #12.

**Closed by iangilman** 2017-11-16 18:56 UTC
